explore_node:
  ros__parameters:
    robot_base_frame: base_footprint
    costmap_topic: /global_costmap/costmap
    costmap_updates_topic: /global_costmap/costmap_updates
    visualize: true
    planner_frequency: 0.33      # How often does it recalculate targets (once every 3 seconds is enough)
    progress_timeout: 10.0       # (It was 30.0) If it doesn’t move within 10 seconds, forget about this goal!
    potential_scale: 2.0         # (Was 3.0) DISTANCE WEIGHT. The higher it is, the more he wants to explore what's CLOSER.
    orientation_scale: 0.0       # Orientation weight (keeping it at 0)
    gain_scale: 3.0              # (Was 1.0) SIZE WEIGHT. We reduce it so he doesn't chase huge patches at the other end of the map.
    transform_tolerance: 0.3
    min_frontier_size: 1      # (Was 0.5) Ignore small holes and lidar noise (size in meters)